# Author: Rosé Pine <hi@rosepinetheme.com>

# Upstream: https://github.com/rose-pine/helix
# Contributing:
#   Please submit changes to https://github.com/rose-pine/helix.
#   The Rosé Pine team will update Helix, including you as a co-author.

inherits = "rose_pine_moon"

"ui.background" = {}



